//
//  Notifications.h
//  StringerX
//
//  Created by Tony Wang on 8/17/13.
//  Copyright (c) 2013 Tony Wang. All rights reserved.
//

#define STRINGER_LOGIN_STATUS_NOTIFICATION @"STRINGER_LOGIN_STATUS_NOTIFICATION"
#define SELECTED_ROW_CHANGE_NOTIFICATION @"SELECTED_ROW_CHANGE_NOTIFICATION"
#define REFRESH_NOTIFICATION @"REFRESH_NOTIFICATION"